### PR TITLE
prepare 2.6.2 version

### PR DESCRIPTION
**Pull request by monteiro**

### CODE REVIEW

**Comment by bdunogier** [comment]
Any chance https://github.com/willdurand/BazingaJsTranslationBundle/pull/191 could make it into 2.6.2 ? It would help me a lot :)

**Comment by stof** [comment]
no there is no change. 2.6.2 was released 1 month ago, and a release cannot change

**Comment by bdunogier** [comment]
That's true... sorry :)

Do you have a date for a 2.7 release ?

**Comment by stof** [comment]
no, because I'm not the maintainer of this repo. @monteiro is

**Pull request merged**
