### PR TITLE
Change autoloading to use PSR-4

### PR DESCRIPTION
**Pull request by jvasseur**
Use psr-4 for autoloading instead of the deprecated target-dir option.

### CODE REVIEW

**Comment by jvasseur** [comment]
L'erreur travis est du a composer : l'extension openssl n'est pas disponible sur php5.3.3

**Comment by stof** [comment]
:+1: for that. ``target-dir`` should be considered a legacy setting in Composer.

**Comment by tgabi333** [comment]
+1

**Comment by stof** [comment]
@monteiro any plan to merge this ?

**Comment by jvasseur** [comment]
I rebased the PR to fix the build.

**Comment by stof** [comment]
👍

**Comment by monteiro** [comment]
Thanks @jvasseur !

**Pull request merged**
