### PR TITLE
Fix: Generate translator-min.js again because of syntax errors

### LINKED ISSUE #195: Minimized version of translator doesn't have semicolon at the end
translator.min.js doesn't have semicolon at the end so it throws error:
`TypeError: (intermediate value)(...) is not a function`

### PR DESCRIPTION
**Pull request by monteiro**
Fixes #195 

//cc @thomas2411

### CODE REVIEW

**Comment by webmaser** [comment]
Please, can you merge it / tag it into 2.6.*?

Thanks.

**Comment by monteiro** [comment]
@webmaser sure!

**Comment by monteiro** [comment]
@webmaser just generated a new version: 2.6.31.

**Comment by webmaser** [comment]
@monteiro Thanks! Works fine.

**Pull request merged**
