### PR TITLE
Check the commonJS before AMD dependency for intl-messageformat

### LINKED ISSUE #303: The dependancy IntlMessageFormat was not found in ./node_modules/bazinga-translator/js/translator.js
Hello,

I got an error when I try to import Translator from 'bazinga-translator'
```
This dependency was not found:

* IntlMessageFormat in ./node_modules/bazinga-translator/js/translator.js

To install it, you can run: npm install --save IntlMessageFormat
```

Here are the steps that I did to get this error:

1. Required the bundle via Composer and Yarn
2. Required the intl-messageformat via Yarn
3. Added this to my base template
```
<html lang="{{ app.request.locale|split('_')[0] }}">
<script src="{{ url('bazinga_jstranslation_js') }}"></script>
```
4. Added this to my js file
```
import Translator from 'bazinga-translator';
```
5. Used Webpack to build the files

### PR DESCRIPTION
**Pull request by ChristianVermeulen**
Due to Webpack supporting both AMD ánd CommonJS we need to check for CommonJS first because the AMD definition is not compatible with Webpacks dependency loading.

This fixes #303 by changing the order of checking the intl-messageformat dependency.

### CODE REVIEW

**Comment by stof** [comment]
I would also change the AMD dependency to use the official package name of the dependency actually (which is also how the file is named in the package)

**Comment by ChristianVermeulen** [comment]
@stof I have updated the package name!

**Review by stof — APPROVED** [review]
Looks good to me

**Comment by drazik** [comment]
Is it planned to merge this fix soon?

**Comment by drazik** [comment]
This PR has been merged (thanks for this), but it seems no new bazinga-translator npm package release was published. Is it planned to publish the fixed npm package?

**Comment by kl3sk** [comment]
Thoses fixes works for Webpack my build too, please @monteiro and/or @stof  update the package.

Thank you

**Comment by monteiro** [comment]
@kl3sk I have updated the package to version 4.0.1. Enjoy! 🥳

**Comment by arnespremberg** [comment]
hi @monteiro I am still getting this error, even though I'm on v4.0.1 - any ideas? Thanks!

**Comment by monteiro** [comment]
Does it work with master?

**Comment by arnespremberg** [comment]
Thanks for getting back! In the end I got it to work, even though the message I got was the same the error was connected to a confusion in node_modules folders. Sorry for bothering you!

**Pull request merged**
