### PR TITLE
Add tilde to Symfony 4.0 version constraint

### PR DESCRIPTION
**Pull request by GawainLynch**
I gather this was a typo in #224 :smiley_cat:

### CODE REVIEW

**Comment by willdurand** [comment]
maybe dev requirements could benefit of the version 4 too.

**Comment by GawainLynch** [comment]
Sure, give me a few minutes and I'll update :+1:

**Comment by monteiro** [comment]
@GawainLynch oops. :) Can you fix it in another PR?

**Comment by GawainLynch** [comment]
Yep, zero stress :smile_cat:

**Pull request merged**
