### PR TITLE
rename version to 2.6.4 to respect semantic versioning

### PR DESCRIPTION
**Pull request by monteiro**
//cc @stof @boriskaraivanov

### CODE REVIEW

**Comment by stof** [comment]
you will also have to delete the 2.6.31 tag (both locally and in github) and delete the version from Packagist

**Comment by stof** [comment]
and then, hoping that almost no contributor fetched the repo in the meantime, or that you never fetch from their clone, to avoid reintroducing the tag...

**Comment by monteiro** [comment]
@stof the only issue I have is with npm. I can't unpublish. When I unpublish it throws a 403 error. Anyway, I deprecated the old versioning package. 

I have already fixed github.

**Comment by stof** [comment]
npmjs only allows to unpublish versions yourselves within 24 hours. After that, it requires sending a mail to the support: http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy

**Comment by monteiro** [comment]
@stof I'm going to email them then.

**Comment by monteiro** [comment]
@stof version 2.6.31 completely removed (from github and npm)

**Pull request merged**
