### PR TITLE
Remove unnecessary use of `Translator` in getTranslations.js.twig

### PR DESCRIPTION
**Pull request by ruudk**
No need to call `Translator` when it's injected already. Just use short `t`. 

For larger files it will help shave of some bytes on every request :)

### CODE REVIEW

**Comment by monteiro** [comment]
@ruudk In this case you're just renaming Translator for t. There is no need for that because uglify also compresses the file. Have you seen translator.min.js? You can generate it when you run "npm run build".

**Comment by stof** [comment]
@monteiro this is not about the translator file itself, but about the translation files which are generated on the fly or dumped. These ones are not uglified

**Comment by ruudk** [comment]
@stof Indeed. I include `bazinga_jstranslation_js` in every request. That one is automatically generated and cached.

**Comment by stof** [comment]
👍 for these changes

**Pull request merged**
