### PR TITLE
Prevent translation files overwriting files from addResource calls

### PR DESCRIPTION
**Pull request by carakas**
array_merge with replace the translations that are in there while array_merge_recursive will append them. That way you don't loose translation sources.

### CODE REVIEW

**Comment by carakas** [comment]
@monteiro Hi, I'm the maintainer of [Fork CMS](https://github.com/forkcms/forkcms).
I'm looking at using this bundle in our upcoming release but noticed that the translation files that we register get overwritten.
Since this is blocking for us I was wondering if it would be possible to merge and release this fix fast.
If it wouldn't be possible please let me know as well so I can look for an alternative

Kind regards

Carakas

**Comment by monteiro** [comment]
Thanks for the PR @carakas,
Tests are failing for some reason.

**Comment by monteiro** [comment]
@carakas can you rebase, so we can see if all tests are green? Thanks!

**Comment by monteiro** [comment]
It's green. I will release next week if everything is fine.

**Pull request merged**
